window.CapibikersPortalData = {
  clubName: "Capibikers",
  claim: "Lenti ma incazzati.",
  headline: "Il portale ufficiale delle scorribande a passo capibara",
  subheadline:
    "Tra coast road, soste sacre e deviazioni sempre difendibili, qui vive il diario semiserio della compagnia.",
  intro:
    "Un mappamondo per segnare i passaggi del branco, ricordare dove si e mangiato bene e decidere quale curva affrontare alla prossima uscita.",
  instagramProfileUrl: "https://www.instagram.com/capibikersofficial/",
  suggestionCandidates: [
    {
      name: "Arbatax",
      country: "Italy",
      lat: 39.9333,
      lng: 9.7075,
      reason: "continua la costa est con mare, porto e strada perfetta per un'altra apparizione",
    },
    {
      name: "Bari Sardo",
      country: "Italy",
      lat: 39.8414,
      lng: 9.644,
      reason: "spinge il giro piu in la senza perdere il ritmo lento ma serio",
    },
    {
      name: "Baunei",
      country: "Italy",
      lat: 40.0307,
      lng: 9.6642,
      reason: "montagna e costa si stringono la mano e fanno venire voglia di rimettere il casco",
    },
    {
      name: "Cala Gonone",
      country: "Italy",
      lat: 40.2835,
      lng: 9.6347,
      reason: "abbastanza lontana da sentirsi spedizione, abbastanza bella da meritare il casino",
    },
    {
      name: "Villasimius",
      country: "Italy",
      lat: 39.144,
      lng: 9.5178,
      reason: "ottima per una sortita piu leggera ma comunque scenografica",
    },
    {
      name: "Bosa",
      country: "Italy",
      lat: 40.2995,
      lng: 8.5006,
      reason: "lungomare, curve e ottimi motivi per far diventare il rientro secondario",
    },
    {
      name: "Alghero",
      country: "Italy",
      lat: 40.557,
      lng: 8.3193,
      reason: "porto, sole e kilometraggio raccontabile per settimane",
    },
  ],
  spots: [
    {
      id: "cagliari-bodie-art",
      name: "Cagliari",
      venue: "Bodie Art",
      country: "Italy",
      lat: 39.2238,
      lng: 9.1282,
      year: "2026",
      address: "Via San Giovanni 254, Cagliari",
      story: "Checkpoint urbano tra motori, amici e liturgia della serata fatta bene.",
      caption: "",
      instagramUrl: "",
      photoUrl: "",
    },
    {
      id: "monastir-bulldog-hamburgeria",
      name: "Monastir",
      venue: "Bulldog Hamburgeria",
      country: "Italy",
      lat: 39.3894,
      lng: 9.0446,
      year: "2026",
      address: "Via Michelangelo Buonarroti 10, Monastir",
      story: "Pausa tattica carburata a carne, rumore e pianificazione del prossimo casino.",
      caption: "",
      instagramUrl: "",
      photoUrl: "",
    },
    {
      id: "santa-maria-navarrese",
      name: "Santa Maria Navarrese",
      venue: "Santa Maria Navarrese",
      country: "Italy",
      lat: 39.9903,
      lng: 9.684,
      year: "2026",
      address: "Santa Maria Navarrese, Ogliastra",
      story: "Tappa costiera da manuale: visuale larga, strada giusta, zero fretta.",
      caption: "",
      instagramUrl: "",
      photoUrl: "",
    },
  ],
};
